#! /bin/sh

xsetroot -cursor_name left_ptr
picom -f &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
feh --bg-fill /$HOME/.config/gruv.jpg &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding            30
bspc config bottom_padding         10
bspc config left_padding           10
bspc config right_padding          10
#bspc config top_padding            40
#bspc config bottom_padding         30
#bspc config left_padding           20
#bspc config right_padding          20



bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
wmname compiz &

bspc config normal_border_color    "#4a4a4a"
bspc config active_border_color    "#848484"
bspc config focused_border_color   "#ebdbb2"
bspc config split_ratio            0.52
bspc config borderless_monocle     false
bspc config gapless_monocle        true
bspc config single_monocle         true
bspc config pointer_modifier       mod4
bspc config pointer_action1        move
bspc config pointer_action2        resize_corner
bspc config focus_follows_pointer  true
